from typing import Optional, Annotated
from pydantic import BaseModel,Field

    
class InputState(BaseModel):
    track_id: str=Field(min_length=3,description="The UUID for the essay submission request")
    question: str=Field(min_length=1,description="The IELTS essay question")
    essay: str=Field(min_length=1,description="Essay submitted for grading")
    essay_type: int=Field(2,ge=1,le=4,description="Integer representation of writing task: 1 - General Writing 1; 2 - General Writing 2; 3 - Academic Writing 1; 4 - Academic Writing 2")
    target_band: int=Field(9,ge=1,le=9,description="Target band score selected by the student.")
    image_url: Optional[str] = Field(default=None,description="URL of the image for Academic Writing Task 1")
    image_description: Optional[str]=Field(description="A short summarised description of the image contained in the image_url",default=None)
    
class GrammarOutputState(BaseModel):
    grammar_score: int=Field(ge=0,le=9,description="The IELTS Grammatical Range and Accuracy band score from 0 to 9 for the provided essay and question")
    grammar_comment: str=Field(description="Brief comments explaining the reason for the IELTS Grammatical Range and Accuracy band score and suggestions to meet the target band.",min_length=3)

class CoherenceOutputState(BaseModel):
    coherence_score: int=Field(ge=0,le=9,description="The IELTS Coherence and Cohesion band score from 0 to 9 for the provided essay and question")
    coherence_comment: str=Field(description="Brief comments explaining the reason for the IELTS Coherence and Cohesion band score and suggestions to meet the target band.",min_length=3)

class ToolState(InputState):
    task_tool_output: Optional[str] = None
    criteria_tool_output: Optional[str] = None
    band_tool_output: Optional[str] = None

class LexicalOutputState(BaseModel):
    lexical_score: int=Field(ge=0,le=9,description="The IELTS Lexical Resource band score from 0 to 9 for the provided essay and question")
    lexical_comment: str=Field(description="Brief comments explaining the reason for the IELTS Lexical Resource band score and suggestions to meet the target band.",min_length=3)

class ImageDescriptionOutput(BaseModel):
    image_description: Optional[str]=Field(description="A short summarised description of the image contained in the image_url",default=None)

class TaskAgentOutput(BaseModel):
    task_score: int=Field(ge=0,le=9,description="The IELTS Task Achievement band score from 0 to 9 for the provided essay and question")
    task_comment: str=Field(description="Brief comments explaining the reason for the IELTS Task Achievement band score and suggestions to meet the target band.",min_length=3)

class TaskOutputState(TaskAgentOutput,ImageDescriptionOutput):
    pass

class OutputState(GrammarOutputState,CoherenceOutputState,LexicalOutputState,TaskOutputState):
    track_id: str=Field(min_length=3,description="The UUID for the essay submission request")
    overall_feedback: str=Field(min_length=3,default="Overall Feedback Not Generated",description="Actionable feedback or improvement plan.")

class CentralAgentState(InputState):
    grammar_score: Optional[int]=Field(default = None, ge=0,le=9)
    coherence_score: Optional[int]=Field(default = None, ge=0,le=9)
    lexical_score: Optional[int]=Field(default = None, ge=0,le=9)
    task_score: Optional[int]=Field(default = None, ge=0,le=9)
    grammar_comment: Optional[str] = None
    coherence_comment: Optional[str] = None
    lexical_comment: Optional[str] = None
    task_comment: Optional[str] = None
    overall_feedback: str=Field(min_length=3,default="Overall Feedback Not Generated")  
    


class EvaluationOutputState(BaseModel):
    Task_Accuracy: dict | None = None
    Grammar_Evaluation_Quality: dict | None = None
    Lexical_Evaluation_Quality: dict | None = None
    Coherence_Evaluation_Quality: dict | None = None
    Feedback_Quality: dict | None = None
    meta_summary: dict | None = None
    usage_metadata: dict | None = None 



class GapAnalysisOutputState(OutputState):
    """Structured output of the Gap Analysis Agent."""
    # track_id: str = Field( description="Unique identifier for tracking essay evaluation.")
    # target_band: int = Field( ge=1, le=9, description="Target band score set for the essay.")
    overall_band: float = Field(ge=0.0, le=9.0, description="Computed average band score across all criteria.")
    met_target: bool = Field(description="Whether the essay met or exceeded the target band.")
    weak_bands: dict[str, int] = Field(description="Dictionary of weak criteria and their current band scores (below target).")
    overall_feedback: str = Field( description="Actionable feedback or improvement plan generated by the LLM." )
    descriptors_used: Optional[dict[str, dict]] = Field(default=None, description="Target band descriptors per weak criterion used to generate the improvement plan.")
    assessment_criteria_used: Optional[dict[str, dict]] = Field(default=None, description="Assessment criteria per weak criterion used in the analysis.")


